### ISSUE TITLE
Path in asserts can't be resolved with wildcards

### ISSUE THREAD

**Issue by zhuchcn** [uclahs-cds/tool-NFTest#63]
We often use wildcards for the output file path to assert. For example, the line below shows how we specify the final BAM file to verify.

https://github.com/uclahs-cds/pipeline-align-RNA/blob/e87489665b4a7ded90ee27efd5c6ccb81796e730/nftest.yml#L16

Currently, `NFTestAssert`s are created directly from the key-value pairs under `assert` in the test yaml file.

https://github.com/uclahs-cds/tool-NFTest/blob/2e132a1cb4f3af04997fcb3138a3d3d5ee7e78aa/nftest/NFTestRunner.py#L30

And here we check whey the the path exists.

https://github.com/uclahs-cds/tool-NFTest/blob/2e132a1cb4f3af04997fcb3138a3d3d5ee7e78aa/nftest/NFTestAssert.py#L34

But unfortunately, `pathlib.Path` does not expand the wildcards automatically. See below.

```python
In [1]: from pathlib import Path
In [2]: Path('/hot/software/pipeline/pipeline-align-RNA/Nextflow/development/unreleased/czhu-fix-star/A_mini_01-STAR/align-RNA-*/CPCG0196-F1-A-mini-01/STAR-*/output/STAR-*_GATK-*_A-mini_CPCG0196-F1-A-mini-01.bam').exists()
Out[2]: False
```

**Comment by yashpatel6** [comment]
The tests are currently set up to resolve the paths before calling the existence assertion, is there a case where the existence check is called without calling the resolution function?

**Comment by zhuchcn** [comment]
Oh yeah I saw this:

https://github.com/uclahs-cds/tool-NFTest/blob/2e132a1cb4f3af04997fcb3138a3d3d5ee7e78aa/nftest/common.py#L37-L44

Then I must have been using the old version of nftest.
